### ISSUE TITLE
Broader Error Handling

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/slayer#42]
We ought to wrap all calls to `call` with a `begin`/`rescue` so we can handle all failures with the same mechanism.

Cautionary note: we should have two rescue's:

```
begin
  call #...
rescue StandardError => e
  fail! wrap_error(e)
rescue => e
  fail! wrap_error(e)
  raise
end
```

This allows handling the unexpected non-standard error, but then still failing, since you should never rescue `Exception` in ruby.

**Comment by ncallaway** [comment]
I'm adding to the 0.4.0 milestone. Let's discuss the inclusion of this, and how it applies if we add the result mechanisms to services.

Should Service _also_ wrap exceptions and only bubble up a Result, or should we give you more leeway to raise an exception out of a service?

**Comment by wkirby** [comment]
In the _original_ design, I pretty intentionally _didn't_ do this, because I didn't want to interrupt unintentional errors. If an unhandled exception is happening deep within a `command` or `service`, I don't want that to be obscured by the `slayer` machinery. If it's an exception you're intentionally throwing, I think a better pattern is something like:

```ruby
class FooCommand < Slayer::Command
    def call
        method_that_might_raise_my_exception
        pass!
    rescue MyException e
        fail! :my_exception, e
    end
end
```

My _personal_ take (and I'm happy to debate the merits of this opinion), is that the smaller footprint we have, the better.

**Comment by Crisfole** [comment]
People generally don't purposely throw uncaught exceptions. As a rule the errors that make it this high on the stack are going to cause trouble. This just forces you to handle the error.

**Comment by wkirby** [comment]
That's sort of my point. I think any exception that makes it this high without being handled shouldn't be wrapped by our code — to me that just serves to obfuscate what's actually happening.

Perhaps I'm missing something though.

**Comment by Crisfole** [comment]
I'm not invested enough​ to care​ either way. I prefer my way of course, but it's enough to document the expected error handling technique.

**Comment by Crisfole** [comment]
I landed with you. Specifically because of the `better_errors` gem which is useless without an uncaught error.
